### ISSUE TITLE
Number to char

### ISSUE THREAD

**Issue by Harvie** [MaxRomagnoli/DIY-analog-dialer-to-USB-keyboard#1]
replace this crazy stuff:

```C
...
    else if (count == 2) {
      Keyboard.print('2');
    }
...
```

with something like this:
```C
      Keyboard.print('0'+count);
```

maybe some explicit type casting will be required.

Or just use my library. Uses interrupts and only needs one wire instead of two :-)
https://github.com/harvie/rotarydial

**Comment by MaxRomagnoli** [comment]
Maybe i can try this if it looks nicer, but i have to try it
`else if (count > 0 and count <10) {
      Keyboard.print((String)count);
    count = 0;
  } else if (count == 10) {
      Keyboard.print('0');
    count = 0;
  }`

**Comment by mo-g** [comment]
Raised #2.

**Comment by MaxRomagnoli** [comment]
Thanks @mo-g

**Comment by mo-g** [comment]
The `>=` was a nice call. :)
